/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2qQZt5tRlFR
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { WavyBackground } from "./ui/wavy-background";

export function Subscribe() {
  return (
    <div className="bg-gray-50/70 dark:bg-gray-950/70 py-12 md:py-24">
      <div className="container flex flex-col items-center justify-center gap-4 px-4 text-center md:gap-10 md:px-6">
        <div className="space-y-3 text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Learning Begins.<br/> Start Your Journey Now.</h2>
         
          <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Sign up for our newsletter to get the latest news, updates, and special offers delivered to your inbox.
          </p>
         
        </div>
        <div className="flex flex-col gap-2 min-[400px]:flex-row">
          <Input className="max-w-xs w-full md:max-w-sm" placeholder="Enter your email" type="email" />
          <Button size="lg">Subscribe</Button>
        </div>
      </div>
    </div>
  )
}
